### ISSUE TITLE
Changing navbar position to top

### ISSUE THREAD

**Issue by tunayuyar** [xvello/homepage-navigation#1]
Hi,

I know this will be simple for people knows what they are doing, but I couldnt manage to change navbar position to top.

Could you help?

Thanks.

Tunay.

**Comment by xvello** [comment]
Hello Tunay,

To change the navbar position, one needs to modify the CSS style of several classes, but it's doable.
Could you please describe the end result you are looking for? Would the navbar stay 64px thick? A mockup would be great.

Regards

**Comment by tunayuyar** [comment]
Hi,

Thanks for reply. I can change thickness, icons, fonts, add icons etc. Only thing I cant do is changing position. Im using one in here http://duyur.us but need for another website that will work better at top.

**Comment by xvello** [comment]
Hi, 

I Commited a new version with optional horizontal mode. Could you please check it out and modify the html element from vn to hn?

**Comment by tunayuyar** [comment]
Hi,

Yes it works as intended. You can check it out at http://sorun.us .

**Comment by xvello** [comment]
Great! Hit me up if you need more customization options.
